name: Mohit Bot Auto-Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Every hour bot ko automatically run karega
  workflow_dispatch:  # Manually run karne ka option

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 🔥 Repository Clone
        uses: actions/
